// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class BrightcoveVideo
    {
        public const string Codename = "brightcove_video";
        public const string VideoIframeCodename = "video_iframe";
        public const string VideoTitleCodename = "video_title";

        public ContentItemSystemAttributes System { get; set; }
        public string VideoIframe { get; set; }
        public string VideoTitle { get; set; }
    }
}