// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class CallToActionModel
    {
        public const string Codename = "call_to_action";
        public const string ButtontextCodename = "buttontext";
        public const string CallToActionCodename = "call_to_action";
        public const string ExternalUrlCodename = "external_url";
        public const string InternalAssetCodename = "internal_asset";
        public const string NameCodename = "name";
        public const string OpenInNewWindowCodename = "open_in_new_window_";
        public const string TextCodename = "text";
        public const string TitleCodename = "title";

        public string Buttontext { get; set; }
        public IEnumerable<object> CallToAction { get; set; }
        public string ExternalUrl { get; set; }
        public IEnumerable<Asset> InternalAsset { get; set; }
        public string Name { get; set; }
        public IEnumerable<MultipleChoiceOption> OpenInNewWindow { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public IRichTextContent Text { get; set; }
        public string Title { get; set; }
    }
}