// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class Copy
    {
        public const string Codename = "copy";
        public const string ImageCodename = "image";
        public const string ImageStyleCodename = "image_style";
        public const string SectionTitleCodename = "section_title";
        public const string TextCodename = "text";
        public const string TypeCodename = "type";
        public const string WidgetNameCodename = "widget_name";

        public IEnumerable<Asset> Image { get; set; }
        public IEnumerable<MultipleChoiceOption> ImageStyle { get; set; }
        public string SectionTitle { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public IRichTextContent Text { get; set; }
        public IEnumerable<MultipleChoiceOption> Type { get; set; }
        public string WidgetName { get; set; }
    }
}