// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class EmbeddedVideo
    {
        public const string Codename = "embedded_video";
        public const string AllowfullscreenCodename = "allowfullscreen";
        public const string HeightCodename = "height";
        public const string LinkCodename = "link";
        public const string NameCodename = "name";
        public const string WidthCodename = "width";

        public IEnumerable<MultipleChoiceOption> Allowfullscreen { get; set; }
        public decimal? Height { get; set; }
        public string Link { get; set; }
        public string Name { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public decimal? Width { get; set; }
    }
}