// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class EmbeddedFormStack
    {
        public const string Codename = "embedded_form_stack";
        public const string HeightCodename = "height";
        public const string NameCodename = "name";
        public const string SlugCodename = "slug";
        public const string TextCodename = "text";
        public const string TitleCodename = "title";
        public const string WidthCodename = "width";

        public decimal? Height { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public IRichTextContent Text { get; set; }
        public string Title { get; set; }
        public decimal? Width { get; set; }
    }
}