// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class ExternalLink
    {
        public const string Codename = "external_link";
        public const string LinkTargetCodename = "link_target";
        public const string LinkTitleCodename = "link_title";
        public const string NewTabCodename = "new_tab_";

        public string LinkTarget { get; set; }
        public string LinkTitle { get; set; }
        public IEnumerable<MultipleChoiceOption> NewTab { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}