// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class Footer
    {
        public const string Codename = "footer";
        public const string ContactEmailCodename = "contact_email";
        public const string ContactPhoneCodename = "contact_phone";
        public const string ExternalLinksCodename = "external_links";
        public const string LinksCodename = "links";
        public const string NameCodename = "name";

        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public IEnumerable<object> ExternalLinks { get; set; }
        public IEnumerable<object> Links { get; set; }
        public string Name { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}