// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class Homepage
    {
        public const string Codename = "homepage";
        public const string ChildrenCodename = "children";
        public const string HeroImageCodename = "hero_image";
        public const string HeroLinksCodename = "hero_links";
        public const string HeroTextCodename = "hero_text";
        public const string IntroTextCodename = "intro_text";
        public const string MecpLogoCodename = "mecp_logo";
        public const string MetadataCodename = "metadata";
        public const string NameCodename = "name";
        public const string PageTitleCodename = "page_title";
        public const string PromoZoneCodename = "promo_zone";
        public const string SlugCodename = "slug";

        public IEnumerable<Page> Children { get; set; }
        public IEnumerable<Asset> HeroImage { get; set; }
        public IEnumerable<Page> HeroLinks { get; set; }
        public IRichTextContent HeroText { get; set; }
        public IRichTextContent IntroText { get; set; }
        public IEnumerable<Asset> MecpLogo { get; set; }
        public string Metadata { get; set; }
        public string Name { get; set; }
        public string PageTitle { get; set; }
        public IEnumerable<Promo> PromoZone { get; set; }
        public string Slug { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}