// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class HtmlBlock
    {
        public const string Codename = "html_block";
        public const string HtmlContentCodename = "html_content";

        public string HtmlContent { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}