// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class ImageModel
    {
        public const string Codename = "image";
        public const string AltTagCodename = "alt_tag";
        public const string FloatDirectionCodename = "float_direction";
        public const string ImageCodename = "image";
        public const string MarginBottomCodename = "margin_bottom";
        public const string MarginLeftCodename = "margin_left";
        public const string MarginRightCodename = "margin_right";
        public const string MarginTopCodename = "margin_top";
        public const string TitleCodename = "title";

        public string AltTag { get; set; }
        public string FloatDirection { get; set; }
        public IEnumerable<Asset> Image { get; set; }
        public decimal? MarginBottom { get; set; }
        public decimal? MarginLeft { get; set; }
        public decimal? MarginRight { get; set; }
        public decimal? MarginTop { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}