// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class LayoutStudyGuideList
    {
        public const string Codename = "layout___study_guide_list";
        public const string NameCodename = "name";
        public const string WidgetZoneCodename = "widget_zone";

        public string Name { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public IEnumerable<object> WidgetZone { get; set; }
    }
}