// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class Page
    {
        public const string Codename = "page";
        public const string AlternateSlugsCodename = "alternate_slugs";
        public const string ChildrenCodename = "children";
        public const string MetadataCodename = "metadata";
        public const string NameCodename = "name";
        public const string ParentCodename = "parent";
        public const string SlugCodename = "slug";
        public const string TitleCodename = "title";
        public const string WidgetZoneCodename = "widget_zone";

        public string AlternateSlugs { get; set; }
        public IEnumerable<object> Children { get; set; }
        public string Metadata { get; set; }
        public string Name { get; set; }
        public IEnumerable<object> Parent { get; set; }
        public string Slug { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
        public IEnumerable<object> WidgetZone { get; set; }
    }
}