// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class Promo
    {
        public const string Codename = "promo";
        public const string BackgroundImageCodename = "background_image";
        public const string DescriptionCodename = "description";
        public const string LinkedPageCodename = "linked_page";
        public const string TitleCodename = "title";

        public IEnumerable<Asset> BackgroundImage { get; set; }
        public IRichTextContent Description { get; set; }
        public IEnumerable<object> LinkedPage { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}