// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class SimplePage
    {
        public const string Codename = "simple_page";
        public const string DescriptionCodename = "description";
        public const string NavigationNavigationCodename = "navigation__navigation";
        public const string NavigationSubNavigationTitleCodename = "navigation__sub_navigation_title";
        public const string SlugCodename = "slug";
        public const string TitleCodename = "title";

        public IRichTextContent Description { get; set; }
        public IEnumerable<TaxonomyTerm> NavigationNavigation { get; set; }
        public string NavigationSubNavigationTitle { get; set; }
        public string Slug { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}