// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class StudyGuide
    {
        public const string Codename = "study_guide";
        public const string DetailsCodename = "details";
        public const string ImageCodename = "image";
        public const string TitleCodename = "title";

        public IRichTextContent Details { get; set; }
        public IEnumerable<Asset> Image { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}