// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace mecp_kontent_core.Models
{
    public partial class Testak
    {
        public const string Codename = "testak";
        public const string BodyCodename = "body";
        public const string PagesCodename = "pages";
        public const string SummaryCodename = "summary";
        public const string TitleCodename = "title";
        public const string UntitledUrlSlugCodename = "untitled_url_slug";

        public IRichTextContent Body { get; set; }
        public IEnumerable<object> Pages { get; set; }
        public string Summary { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
        public string UntitledUrlSlug { get; set; }
    }
}